<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Squirrel Syntax: version 0.1</string>
    <key>fileTypes</key>
	<array>
		<string>nut</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Squirrel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.squirrel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.squirrel</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.squirrel</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.squirrel</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(class)\s+([a-zA-Z_](?:\w|\.)*)(?:\s+(extends)\s+([a-zA-Z_](?:\w|\.)*))?</string>
			<key>name</key>
			<string>meta.class.squirrel</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.squirrel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(function)\s*([a-zA-Z0-9_]*)\s*\((\s*[a-zA-Z0-9_]*\s*)\)</string>
			<key>name</key>
			<string>other.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(constructor)\s*\((.*)\)</string>
			<key>name</key>
			<string>other.constructor</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(::[a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>other.global</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|while|do|switch|for|foreach|return|throw|yield|continue|catch|resume|default|else|case|print)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(local|class|function|constructor|enum)\b</string>
			<key>name</key>
			<string>storage.type.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(extends|static|const)\b</string>
			<key>name</key>
			<string>storage.modifier.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(delete|in|clone|instanceof|typeof)\b</string>
			<key>name</key>
			<string>keyword.operator.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(base|this)\b</string>
			<key>name</key>
			<string>variable.language.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|%|&amp;|\*|\-\-|\-|\+\+|\+|==|=|!=|&lt;=|&gt;=|&lt;=&gt;|&lt;-|&gt;&gt;&gt;|&lt;&lt;|&gt;&gt;|!|&amp;&amp;|\|\||\?\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|%=|\b(in|instanceof|typeof)\b</string>
			<key>name</key>
			<string>keyword.operator.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.squirrel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.squirrel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.squirrel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.squirrel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.squirrel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.squirrel</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.squirrel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*(?!/)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.squirrel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.squirrel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.squirrel</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.squirrel</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.squirrel</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CloseGarage|CloseSSVBridge|EnableTrains|GetBoundariesLower|GetBoundariesUpper|GetFriendlyFire|GetGamespeed|GetGravity)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(GetHour|GetIslands|GetMinute|GetSSVBridgeLock|GetSSVBridgeUpdateTime|GetSurfaceTraction|GetTimeLock|GetWeather)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(GetWeatherLock|IsSSVBridgeUp|OpenGarage|OpenSSVBridge|SetBoundaries|SetFriendlyFire|SetGamespeed|SetGravity|SetIslands)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(SetSSVBridgeLock|SetSSVBridgeUpdateTime|SetSurfaceTraction|SetTime|SetTimeLock|SetWeather|SetWeatherLock)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FadeCamera|GetCinematicBorder|GetGreenScanLines|GetWhiteScreenLines|RestoreCamera|ShakeCamera|SetCameraMatrix|SetCineMaticBorder)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(SetGreenScanLines|SetWhiteScanLines)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(GetFlyingBoats|GetFlyingCars|GetHandlingCheat|GetTaxiJump|GetWaterCarCheat|SetFlyingBoats|SetFlyingCars|SetHandlingCheat|SetTaxiJump|SetWaterCarCheat)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CreateCheckpoint|CreateClientCheckpoint|Checkpoint\.|FindCheckpoint|GetCheckpointCount)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CreateExplosion|CreateFire|ExtinguishFire|ExtinguishAllFires)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(GetGamemodeName|GetMapName|GetMaxPlayers|GetMTUSize|GetPassword|GetPlayers|GetPort|GetServerName|SetGamemodeName|SetMapName|SetMaxPlayers|SetPassword|SetPort|SetServerName|SetServerRule)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FindObject|CreateObject|BigMessage|ClearMessages|Message|MessageAllExcept|MessagePlayer|PagerMessage|SendPlayerMessage|SmallMessage)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ClearIni|CountIniSection|DeleteIniSection|ReadIniBool|ReadIniFloat|ReadIniIndex|ReadIniInteger|ReadIniString|RemoveIniValue|WriteIniBool|WriteIniFloat|WriteIniInteger|WriniteIniString)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(HashTable|FindHashTable|CallClientFunc|Callfunc|DecScriptData|DelScriptData|GetScriptData|Halt|IncScriptData|LoadMoudle|LoadScript|SetScriptData|UnloadScript)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FindSound|PlayFrontEndSound|PlayFrontEndTRack|PlaySuspectLastSeen|StopFrontEndTrack|AddSpawnClass|AddSpawnScreen|FindSpawnScreen|GetSpawnClassCount)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sqlite_close|sqlite_column_count|sqlite_column_data|sqlite_free|sqlite_next_row|sqlite_open|sqlite_query)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mysql_connect|mysql_close|mysql_query|mysql_num_rows|mysql_num_fields|mysql_fetch_row|mysql_fetch_assoc|mysql_fetch_lengths|mysql_free_result|mysql_errno|mysql_error|mysql_ping|mysql_escape_string|mysql_select_db|mysql_change_user|mysql_warning_count|mysql_affected_rows|mysql_insert_id|mysql_info)\b</strong>
			<key>name</key>
			<strong>keyword.control.squirrel</strong>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(MD5|SHA1|BanIP|BanPlayer|GetBodyPartName|GetDistrictName|KickPlayer|SendRconCommand|UnbanIP|NewSocket|NewTimer|)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sqlite|GetDistance|GetDistance2D|GetFullTime|GetTickCount|GetTime|GetTok|InPoly|IsIn|IsNum|NumTok|RandomString)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CreateVehicle|FindVehicle|GetClosestVehicle|GetVehicleCount|GetVehicleHandlingData|GetVehicleIDFromName|GetVehicleName|SetVehicleHandlingData)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(GetWeaponData|GetWeaponIDFromName|GetWeaponName|SetWeaponData|XmlDocument|XmlElement)\b</string>
			<key>name</key>
			<string>keyword.control.squirrel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.show|\.DisplayType|\.Colour|\.Icon|\.ID|\.Owner|\.Pos|\.Size|\.Remove|\.Radius|\.Type|\.VirtualWorld|\.Angle|\.Model|\.MoveTo|\.RotateTo|\.Stop)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.InstantRespawn|\.Life|\.OneTime|\.Cash|\.Alpha|\.ColouredName|\.ClearWeapons|\.Class|\.Frozen|\.GetIgnored|\.Health|\.Marker|\.IdleTime|\.MarkerScale)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.Ping|\.Name|\.Nametag|\.NametagColour|\.RemoveFromVehicle|\.RemoveLimb|\.Score|\.SetAnim|\.SetBoundaries|\.SetIgnored|\.SetIgnoredBy|\.SetVehicleEnterDoor)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.SetVehicleEnterDoor|\.SetWeapon|\.SetSkin|\.Setspawn|\.SetSpawned|\.Team|\.Vehicle|\.VehicleSeat|\.Velocity|\.WantedLevel|\.Weapon|\.SetWeapon|\.WeaponAmmo|\.WeaponState)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.Connect|\.Delete|\.Send|\.SendClient|\.SendLostConnFunc|\.SetNewConnFunc|\.Start|\.Stop|\.Open|\.Close|\.Play|\.Pause|\.AddWeapon|\.SpawnScreen|\.Colour(1|2))\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.Fix|\.GetAddon|\.GetPassenger|\.GetHandlingData|\.Explode|\.PassengerCount|\.SpawnAngle|\.SpawnPos|\.SetAddon|\.SetEnginestate|\.SetRadio|\.Siren|\.SirenLight)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.TaxiLight|\.Wrecked|\.FirstChild|\.LinkChild|\.LoadFile|\.Name|\.SaveFile|\.Clear|\.FirstChild|\.GetAttribute|\.LinkSibling|\.NextSibling|\.Parent)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\.RemoveAttribute|\.RemoveChild|\.RemoveSibling|\.SetAttribute|\.Text)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nut</string>
	<key>uuid</key>
    <string>CCFF04CD-6736-4CF2-9EEF-BB803B77490D</string>
</dict>
</plist>
